package lxd

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// SeccompEvent represents a detected dangerous syscall in a container.
// Generated by cella's own bpftrace monitoring when a syscall from
// DangerousSyscalls is detected.
//
// Background — LXD seccomp notify limitations:
//   LXD v5.x does NOT expose seccomp notify events via the REST event stream
//   (type=seccomp returns HTTP 400 "isn't a supported event type"). The LXD
//   seccomp intercept mechanism (security.syscalls.intercept.*) is handled
//   internally by LXD daemon — it processes specific syscalls (mknod, mount,
//   bpf, etc.) via its own supervisor and does NOT forward them to external
//   clients for operator approval.
//
//   The interactive operator-approval flow for syscalls therefore uses
//   bpftrace detection (via trace/tracer.go) as the trigger, and applies
//   LXD's security.syscalls.intercept.* config keys to block dangerous
//   syscalls after the operator decides to deny.
type SeccompEvent struct {
	Container string    // container name
	Syscall   string    // syscall name (e.g. "ptrace", "mount")
	SyscallNr int       // syscall number
	PID       int       // PID inside the container (from bpftrace)
	Arch      string    // architecture string (e.g. "x86_64")
	Time      time.Time // event timestamp
	// NotifyID is intentionally empty — LXD seccomp notify is not available
	// via REST API. Kept for future compatibility if LXD exposes this.
	NotifyID string
}

// SeccompVerdict is the operator's decision for a pending seccomp event.
type SeccompVerdict struct {
	Allow bool // true = allow (no-op), false = apply LXD intercept to block syscall
	Errno int  // errno for deny (default 1 = EPERM); informational only
}

// SeccompEventCallback is called for each detected dangerous syscall event.
type SeccompEventCallback func(SeccompEvent)

// ── LXD syscall intercept config keys ──────────────────────────────────────
//
// LXD 5.x exposes per-syscall blocking via security.syscalls.intercept.*
// config keys. These cause LXD to intercept and rewrite (or deny) specific
// syscalls at the LXD daemon level. They are NOT the same as operator-approval
// seccomp notify — they are static policies applied at container start.
//
// Supported keys (confirmed on LXD v5.21.4):
//   security.syscalls.intercept.bpf
//   security.syscalls.intercept.mknod
//   security.syscalls.intercept.mount
//   security.syscalls.intercept.sched_setscheduler
//   security.syscalls.intercept.setxattr
//   security.syscalls.intercept.sysinfo
//
// For deny-only (no intercept): use security.syscalls.deny (BPF filter syntax)
// For allow-only:               use security.syscalls.allow

// InterceptableSyscalls is the set of syscalls that can be blocked via
// LXD's security.syscalls.intercept.* config keys.
var InterceptableSyscalls = []string{
	"bpf",
	"mknod",
	"mount",
	"sched_setscheduler",
	"setxattr",
	"sysinfo",
}

// DangerousSyscalls is the full list of syscalls that cella considers
// dangerous and surfaces to the operator for approval. This is a superset
// of InterceptableSyscalls — not all of these can be blocked via LXD API,
// but all of them are worth monitoring.
var DangerousSyscalls = []string{
	"ptrace",
	"mount",
	"umount2",
	"init_module",
	"finit_module",
	"delete_module",
	"kexec_load",
	"kexec_file_load",
	"bpf",
	"perf_event_open",
	"pivot_root",
	"unshare",
}

// BlockSyscallViaIntercept sets the LXD intercept config key for a syscall,
// causing LXD to block or rewrite it at the daemon level.
// Only works for syscalls in InterceptableSyscalls.
// Returns an error if the syscall is not interceptable via LXD API.
func (c *Client) BlockSyscallViaIntercept(ctx context.Context, containerName, syscall string) error {
	key := fmt.Sprintf("security.syscalls.intercept.%s", syscall)
	err := c.UpdateContainerConfig(ctx, containerName, map[string]string{
		key: "true",
	})
	if err != nil {
		return fmt.Errorf("block syscall %q via LXD intercept: %w", syscall, err)
	}
	return nil
}

// UnblockSyscall removes the LXD intercept config key for a syscall.
func (c *Client) UnblockSyscall(ctx context.Context, containerName, syscall string) error {
	key := fmt.Sprintf("security.syscalls.intercept.%s", syscall)
	return c.UpdateContainerConfig(ctx, containerName, map[string]string{
		key: "",
	})
}

// SetSyscallDenyList sets a custom BPF-syntax deny list for a container.
// Example: "ptrace:errno=1 mount:errno=1 kexec_load:errno=1"
// This uses security.syscalls.deny which is applied at container start.
func (c *Client) SetSyscallDenyList(ctx context.Context, containerName string, syscalls []string) error {
	if len(syscalls) == 0 {
		return c.UpdateContainerConfig(ctx, containerName, map[string]string{
			"security.syscalls.deny": "",
		})
	}
	// BPF deny syntax: "syscall:errno=EPERM syscall2:errno=EPERM ..."
	parts := make([]string, len(syscalls))
	for i, s := range syscalls {
		parts[i] = s + ":errno=1"
	}
	return c.UpdateContainerConfig(ctx, containerName, map[string]string{
		"security.syscalls.deny": strings.Join(parts, " "),
	})
}

// GetSyscallDenyList returns the current custom syscall deny list for a container.
func (c *Client) GetSyscallDenyList(ctx context.Context, containerName string) ([]string, error) {
	cfg, err := c.GetContainerConfig(ctx, containerName)
	if err != nil {
		return nil, err
	}
	raw := cfg.Config["security.syscalls.deny"]
	if raw == "" {
		return nil, nil
	}
	var syscalls []string
	for _, part := range strings.Fields(raw) {
		// strip :errno=N suffix if present
		if idx := strings.Index(part, ":"); idx >= 0 {
			part = part[:idx]
		}
		syscalls = append(syscalls, part)
	}
	return syscalls, nil
}

// ── Stub: SeccompMonitor ────────────────────────────────────────────────────
//
// SeccompMonitor is a stub retained for API compatibility.
// LXD v5.x does not expose a seccomp notify event stream via REST API.
// Real-time dangerous syscall detection is performed by trace/tracer.go
// using bpftrace, which feeds into the TUI approval overlay.
//
// Future: if LXD exposes a seccomp notify socket (like systemd-seccomp or
// libseccomp's SECCOMP_IOCTL_NOTIF_*), this can be wired up to provide
// true kernel-level interception. For now, cella uses bpftrace detection
// + LXD static intercept/deny as the two-step response.
type SeccompMonitor struct {
	socketPath string
	cancel     context.CancelFunc
}

// NewSeccompMonitor creates a SeccompMonitor stub.
func NewSeccompMonitor(socketPath string) *SeccompMonitor {
	return &SeccompMonitor{socketPath: socketPath}
}

// Start is a no-op stub. Dangerous syscall events come from trace/tracer.go.
func (m *SeccompMonitor) Start(ctx context.Context, callback SeccompEventCallback) error {
	// LXD REST API does not support type=seccomp event subscriptions.
	// Syscall events are sourced from bpftrace via trace.Tracer.
	return fmt.Errorf("LXD seccomp event stream not available; use trace.Tracer (bpftrace) for syscall detection")
}

// Stop is a no-op stub.
func (m *SeccompMonitor) Stop() {
	if m.cancel != nil {
		m.cancel()
	}
}

// SendSeccompVerdict is a stub retained for API compatibility.
// With bpftrace-based detection, there is no kernel-level verdict to send —
// cella instead applies security.syscalls.intercept.* or security.syscalls.deny
// to block denied syscalls for future calls.
func (c *Client) SendSeccompVerdict(ctx context.Context, notifyID string, verdict SeccompVerdict) error {
	// No-op: LXD does not expose a seccomp verdict REST endpoint.
	// Use BlockSyscallViaIntercept or SetSyscallDenyList to block syscalls.
	_ = notifyID
	_ = verdict
	return nil
}

// ── Deprecated stubs (kept to avoid compile errors in panels_syscall_approval.go) ──

// EnableSeccompNotify is deprecated. The security.seccomp.notify config key
// does not exist in LXD v5.x. Use security.syscalls.intercept.* instead.
// Kept as a no-op to avoid breaking callers until panels_syscall_approval.go
// is updated to use BlockSyscallViaIntercept / SetSyscallDenyList.
func (c *Client) EnableSeccompNotify(ctx context.Context, containerName string) error {
	// TODO: replace call sites with SetSyscallDenyList(ctx, name, DangerousSyscalls)
	return nil
}

// DisableSeccompNotify is deprecated. See EnableSeccompNotify.
func (c *Client) DisableSeccompNotify(ctx context.Context, containerName string) error {
	// TODO: replace call sites with SetSyscallDenyList(ctx, name, nil)
	return nil
}

// ── Internal helpers used by parseSeccompEvent (kept for future use) ────────

func isInterceptable(syscall string) bool {
	for _, s := range InterceptableSyscalls {
		if s == syscall {
			return true
		}
	}
	return false
}

// isDangerous returns true if the syscall is in the DangerousSyscalls list.
func IsDangerous(syscall string) bool {
	for _, s := range DangerousSyscalls {
		if s == syscall {
			return true
		}
	}
	return false
}

// formatDenyList formats syscall names as a BPF deny list string.
func FormatDenyList(syscalls []string) string {
	parts := make([]string, len(syscalls))
	for i, s := range syscalls {
		parts[i] = s + ":errno=1"
	}
	return strings.Join(parts, " ")
}

// keep time imported
var _ = time.Now
